---
- hosts: hdptomcat9
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
    java_archive: /opt/jdk-8u151-linux-x64.tar.gz
  name: app deployment
  tasks:
    - name: install libselinux-python
      become: yes
      become_method: sudo
      yum:
        name: libselinux-python
        state: present
    - name: copy tomcat9 to /opt
      become: yes
      become_method: sudo
      copy:
        src: files/apache-tomcat-9.0.8.tar.gz
        dest: /opt
        owner: root
        group: root
        mode: 0755
    - name: unpack tomcat
      become: yes
      become_method: sudo
      command: tar xvf /opt/apache-tomcat-9.0.8.tar.gz
    - name: download java
      become: yes
      become_method: sudo
      command: curl {{ download_url }} -O {{ java_archive }}
    - name: make java dir
      become: yes
      become_method: sdo
      file: state=directory path=/usr/java
#     when: not jdk8.stat.exists  
    - name: unpack jdk8
      become: yes
      become_method: sudo
      unarchive:
        src: "{{ java_archive }}"
        dest: /opt
        remote_src: yes
    - name: change ownership
      become: yes
      become_method: sudo
      file:  state=directory path={{java_name}} owner=root group=root recurse=yes

    - name: alternative install1
      become: yes
      become_method: sudo
      command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 50'
    - name: update JCE policy to unlimited
      become: yes
      become_method: sudo
      lineinfile:
        dest=/usr/java/jdk1.8.0_151/jre/lib/security/java.security
        line="crypto.policy=unlimited" 
