---
- hosts: hdptomcat9
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jdk-8u151-linux-x64.tar.gz
    java_archive: /opt/jdk-8u151-linux-x64.tar.gz
  name: app deployment
  tasks:
    - name: install libselinux-python
      become: yes
      become_method: sudo
      yum:
        name: libselinux-python
        state: present
    - name: download java
      become: yes
      become_method: sudo
      command: curl {{ download_url }} -O {{ java_archivve }}
  
